"""initial_schema

Revision ID: 830150613e8f
Revises: 
Create Date: 2026-03-17 10:43:22.608591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830150613e8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('responsible', sa.String(length=20), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bitrix_task_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreements'))
    )
    op.create_index(op.f('ix_agreements_department_id'), 'agreements', ['department_id'], unique=False)
    op.create_index(op.f('ix_agreements_interaction_id'), 'agreements', ['interaction_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('instruction_version', sa.String(length=50), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('scores_detail', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('call_topic', sa.String(length=255), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_department_id'), 'analyses', ['department_id'], unique=False)
    op.create_index('ix_analyses_department_instruction', 'analyses', ['department_id', 'instruction_version'], unique=False)
    op.create_index('ix_analyses_department_manager', 'analyses', ['department_id', 'manager_id'], unique=False)
    op.create_index(op.f('ix_analyses_instruction_version'), 'analyses', ['instruction_version'], unique=False)
    op.create_index(op.f('ix_analyses_interaction_id'), 'analyses', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_analyses_manager_id'), 'analyses', ['manager_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_department_id'), 'insights', ['department_id'], unique=False)
    op.create_index(op.f('ix_insights_interaction_id'), 'insights', ['interaction_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('week_id', sa.String(length=10), nullable=True),
    sa.Column('counted', sa.Boolean(), nullable=False),
    sa.Column('used_for_reco', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions')),
    sa.UniqueConstraint('external_id', name=op.f('uq_interactions_external_id'))
    )
    op.create_index(op.f('ix_interactions_department_id'), 'interactions', ['department_id'], unique=False)
    op.create_index('ix_interactions_department_status', 'interactions', ['department_id', 'status'], unique=False)
    op.create_index('ix_interactions_department_week', 'interactions', ['department_id', 'week_id'], unique=False)
    op.create_index(op.f('ix_interactions_manager_id'), 'interactions', ['manager_id'], unique=False)
    op.create_index(op.f('ix_interactions_status'), 'interactions', ['status'], unique=False)
    op.create_index(op.f('ix_interactions_week_id'), 'interactions', ['week_id'], unique=False)
    op.create_table('manager_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('week_id', sa.String(length=10), nullable=False),
    sa.Column('instruction_version', sa.String(length=50), nullable=False),
    sa.Column('calls_total', sa.Integer(), nullable=False),
    sa.Column('calls_analyzed', sa.Integer(), nullable=False),
    sa.Column('score_avg', sa.Float(), nullable=True),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('top_weakness_1', sa.String(length=255), nullable=True),
    sa.Column('top_weakness_2', sa.String(length=255), nullable=True),
    sa.Column('top_weakness_3', sa.String(length=255), nullable=True),
    sa.Column('top_strength_1', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manager_progress')),
    sa.UniqueConstraint('manager_id', 'week_id', name=op.f('uq_manager_progress_manager_id'))
    )
    op.create_index(op.f('ix_manager_progress_department_id'), 'manager_progress', ['department_id'], unique=False)
    op.create_index('ix_manager_progress_department_week', 'manager_progress', ['department_id', 'week_id'], unique=False)
    op.create_index(op.f('ix_manager_progress_manager_id'), 'manager_progress', ['manager_id'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('bitrix_id', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_managers'))
    )
    op.create_index(op.f('ix_managers_department_id'), 'managers', ['department_id'], unique=False)
    op.create_table('prompt_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('suggested_version', sa.String(length=50), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_suggestions'))
    )
    op.create_index(op.f('ix_prompt_suggestions_department_id'), 'prompt_suggestions', ['department_id'], unique=False)
    op.create_index('ix_prompt_suggestions_department_status', 'prompt_suggestions', ['department_id', 'status'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('critical_errors', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('department_id', 'module', 'version', name=op.f('uq_prompts_department_id'))
    )
    op.create_index(op.f('ix_prompts_department_id'), 'prompts', ['department_id'], unique=False)
    op.create_index('ix_prompts_department_module_active', 'prompts', ['department_id', 'module', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompts_department_module_active', table_name='prompts')
    op.drop_index(op.f('ix_prompts_department_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_prompt_suggestions_department_status', table_name='prompt_suggestions')
    op.drop_index(op.f('ix_prompt_suggestions_department_id'), table_name='prompt_suggestions')
    op.drop_table('prompt_suggestions')
    op.drop_index(op.f('ix_managers_department_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_manager_progress_manager_id'), table_name='manager_progress')
    op.drop_index('ix_manager_progress_department_week', table_name='manager_progress')
    op.drop_index(op.f('ix_manager_progress_department_id'), table_name='manager_progress')
    op.drop_table('manager_progress')
    op.drop_index(op.f('ix_interactions_week_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_status'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_manager_id'), table_name='interactions')
    op.drop_index('ix_interactions_department_week', table_name='interactions')
    op.drop_index('ix_interactions_department_status', table_name='interactions')
    op.drop_index(op.f('ix_interactions_department_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_insights_interaction_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_department_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('departments')
    op.drop_index(op.f('ix_analyses_manager_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_interaction_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_instruction_version'), table_name='analyses')
    op.drop_index('ix_analyses_department_manager', table_name='analyses')
    op.drop_index('ix_analyses_department_instruction', table_name='analyses')
    op.drop_index(op.f('ix_analyses_department_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_agreements_interaction_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_department_id'), table_name='agreements')
    op.drop_table('agreements')
    # ### end Alembic commands ###
